# Generated by Django 5.1.2 on 2024-11-11 19:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_review_body_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, upload_to=blog.models.user_directory_path),
        ),
    ]
